### ISSUE TITLE
Module 'albumentations' has no attribute 'Lambda'

### ISSUE THREAD

**Issue by kkoripl** [DonsetPG/narya#10]
Hi - this time no questions..,

Using script in keypoints_train.py I've tried to start an overview into training time for KeyPointModel on Google Colab, but... got into trouble.

I've copied whole your code from keypoints_train.py, with just small change for arguments loading, but when making object of KeyPointDataset there is an error of module albumentations:
![image](https://user-images.githubusercontent.com/37674650/107579018-d1253180-6bf4-11eb-9d73-f002351d4fbc.png)

I don't know if this is an issue of colab itself, maybe some library version is not suitable, but I cloned all of this repository with installing all requirements into colab.

**Comment by DonsetPG** [comment]
Hey,
Try to update Albumentations to version>=0.3.0 for `Lambda` transform support. 
I’ll make sure it works and take care of that in the requirements.txt tomorrow. 

Let me know if that doesn’t solve the issue.

**Comment by karlosos** [comment]
It's funny because I had same problem today. Upgrading albumentations solved this problem. Simply run following command in notebook cell:

```
!pip install --upgrade albumentations
```

Here is my [colab notebook] where I am trying to learn model. Sadly I still have problems with fitting Keypoints model, altough fitting direct homography model is working. 

[colab notebook]: https://colab.research.google.com/drive/1Ye3TVzEczeSaP-ckangfKGL1OxAdGLMh?usp=sharing

**Comment by kkoripl** [comment]
Yep, that's the solution!

**Comment by DonsetPG** [comment]
Solved in the following [commit](https://github.com/DonsetPG/narya/commit/8c69e778084d4d19c247d420c07d2de3d1173656). 
Thanks for pointing it out!
