### ISSUE TITLE
Keras Models for Homography and Key Points Estimation not using GPU

### ISSUE THREAD

**Issue by Muaz65** [DonsetPG/narya#30]
I am Pytorch User and have not much idea about tensorflow. I am trying to run Keras Models (Homography, Keypoints) on GPU. I have RTX 3090 with CUDA 11.2. I installed Tensorflow-gpu==2.2.0 intsead of simple tensorflow and also tried adding these lines before loading models.
`with tf.device('/GPU:0'):` 
Can you please guide me how can i load these models on GPU instead of CPU.

**Comment by DonsetPG** [comment]
Hey, 
You should try 2 things: 
1. uninstall tensorflow & install tensorflow-gpu
2. uninstall mxnet & install mxnet-cu101

You already did the first step, and since Keras is now fully encapsulated within Tensorflow, it should use your GPU directly. You can make sure of that with:

```python3
import tensorflow as tf
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))
```

2. If it stills do not detect your GPU, try to reinstall a GPU compatible version of mxnet & retry.

Let me know if this helps,
Cheers

**Comment by Muaz65** [comment]
@DonsetPG  tf was detecting GPU. The issue was  with CUDATOOLKIT. When i installed torch with bundled  CUDA 11.0, the model automatically started working on GPU.
